"""added denormed involved veh/cas types

Revision ID: 1595a4eb32f8
Revises: 3c902eeeeea1
Create Date: 2016-01-24 23:05:54.781141

"""

# revision identifiers, used by Alembic.
revision = '1595a4eb32f8'
down_revision = '3c902eeeeea1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('involved_casualty_types', postgresql.BIT(length=100), nullable=True))
    op.add_column('accident', sa.Column('involved_vehicle_types', postgresql.BIT(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accident', 'involved_vehicle_types')
    op.drop_column('accident', 'involved_casualty_types')
    ### end Alembic commands ###
