"""add highway authority and indexes

Revision ID: 3c902eeeeea1
Revises: 71a12c7783fe
Create Date: 2016-01-23 22:40:58.585340

"""

# revision identifiers, used by Alembic.
revision = '3c902eeeeea1'
down_revision = '71a12c7783fe'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accident_accident_severity_id_fkey', 'accident', type_='foreignkey')
    op.drop_table('accident_severity')
    op.add_column('accident', sa.Column('highway_authority_id', sa.String(length=9), nullable=True))
    op.create_index(op.f('ix_accident_date'), 'accident', ['date'], unique=False)
    op.create_index(op.f('ix_accident_date_and_time'), 'accident', ['date_and_time'], unique=False)
    op.create_index(op.f('ix_accident_highway_authority_id'), 'accident', ['highway_authority_id'], unique=False)
    op.create_index(op.f('ix_accident_location'), 'accident', ['location'], unique=False)
    op.drop_index('idx_accident_location', table_name='accident')
    op.drop_constraint('accident_road_class_1_fkey', 'accident', type_='foreignkey')
    op.drop_constraint('accident_road_class_2_fkey', 'accident', type_='foreignkey')
    op.create_foreign_key(None, 'accident', 'casualty_severity', ['severity_id'], ['id'])
    op.drop_column('accident', 'road_class_1')
    op.drop_column('accident', 'road_class_2')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('road_class_2', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('accident', sa.Column('road_class_1', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accident', type_='foreignkey')
    op.create_foreign_key('accident_road_class_2_fkey', 'accident', 'road_class', ['road_class_2'], ['id'])
    op.create_foreign_key('accident_accident_severity_id_fkey', 'accident', 'accident_severity', ['severity_id'], ['id'])
    op.create_foreign_key('accident_road_class_1_fkey', 'accident', 'road_class', ['road_class_1'], ['id'])
    op.create_index('idx_accident_location', 'accident', ['location'], unique=False)
    op.drop_index(op.f('ix_accident_location'), table_name='accident')
    op.drop_index(op.f('ix_accident_highway_authority_id'), table_name='accident')
    op.drop_index(op.f('ix_accident_date_and_time'), table_name='accident')
    op.drop_index(op.f('ix_accident_date'), table_name='accident')
    op.drop_column('accident', 'highway_authority_id')
    op.create_table('accident_severity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('injury_definition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='accident_severity_pkey')
    )
    ### end Alembic commands ###
