"""add sentence part for hit-object-in-carriageway

Revision ID: 7f9894b8b8e4
Revises: 1595a4eb32f8
Create Date: 2016-01-27 20:57:23.651604

"""

# revision identifiers, used by Alembic.
revision = '7f9894b8b8e4'
down_revision = '1595a4eb32f8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hit_object_in_carriageway', sa.Column('sentence_part', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hit_object_in_carriageway', 'sentence_part')
    ### end Alembic commands ###
