"""added highway authority ref data

Revision ID: 8a71f37e3a06
Revises: 9a2cb907fb6d
Create Date: 2016-02-06 10:09:45.871314

"""

# revision identifiers, used by Alembic.
revision = '8a71f37e3a06'
down_revision = '9a2cb907fb6d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highway_authority',
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'accident', 'highway_authority', ['highway_authority_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accident', type_='foreignkey')
    op.drop_table('highway_authority')
    ### end Alembic commands ###
