"""vehicle type fields

Revision ID: 9a2cb907fb6d
Revises: 7f9894b8b8e4
Create Date: 2016-01-27 22:45:37.389279

"""

# revision identifiers, used by Alembic.
revision = '9a2cb907fb6d'
down_revision = '7f9894b8b8e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_type', sa.Column('class_driver', sa.String(), nullable=True))
    op.add_column('vehicle_type', sa.Column('class_passenger', sa.String(), nullable=True))
    op.drop_column('vehicle_type', 'person_label')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_type', sa.Column('person_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vehicle_type', 'class_passenger')
    op.drop_column('vehicle_type', 'class_driver')
    ### end Alembic commands ###
